mongodb-js/mongodb-mcp-server

.prettierignore, .prettierrc.json, FEATURES.md, README.md, dist/client.js, dist/server.js, package-lock.json, package.json, src/client.ts, src/index.ts, src/server.ts, src/state.ts
Recreation of https://github.com/mongodb-labs/atlas-mcp-server/pull/1
=> chore: add prettier

.github/workflows/code_health.yaml, CONTRIBUTING.md, dist/client.js, dist/server.js, eslint.config.js, package-lock.json, package.json, src/client.ts, src/server.ts
- added eslint (via `npm run lint`)
- added github action to check eslint
- changed github action `prettier` to actually check if code needs reformatting
- added `eslint-config-prettier` to make sure eslint does not touch formatting without `prettier`
=> ci: add eslint

scripts/filter.ts, src/common/atlas/client.ts, src/common/atlas/openapi.d.ts, src/config.ts, src/tools/atlas/createAccessList.ts, src/tools/atlas/inspectAccessList.ts, src/tools/atlas/tools.ts
fixes #30 
- added `atlas-inspect-access-list` tool
- added `atlas-create-access-list` tool
=> feat: add atlas access list tools

scripts/filter.ts, src/common/atlas/apiClient.ts, src/common/atlas/auth.ts, src/common/atlas/openapi.d.ts, src/config.ts, src/server.ts, src/state.ts, src/tools/atlas/atlasTool.ts, src/tools/atlas/createDBUser.ts, src/tools/atlas/listClusters.ts, src/tools/atlas/listDBUsers.ts, src/tools/atlas/tools.ts
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/31
- add `atlas-create-db-user` tool
- add `atlas-list-db-users` tool
=> feat: add DB users tools

package-lock.json, package.json, src/common/atlas/apiClient.ts, src/config.ts, src/server.ts, src/state.ts, src/tools/atlas/auth.ts, src/tools/mongodb/connect.ts
Adds the following mechanisms for supplying config (in order of precedence):
- cli args
- environment variables (field names are converted to `MDB_MCP_UPPER_SNAKE_CASE`
- `mongodb-mcp.conf` placed in the `/etc` folder on Unix or `%LOCAL_APP_DATA%\mongodb\mongodb-mcp`.
Fixes #21
=> feat: add support for supplying config options

package-lock.json, package.json, src/common/atlas/auth.ts, src/server.ts, src/state.ts, src/tools/atlas/auth.ts, src/tools/mongodb/connect.ts, src/tools/mongodb/index.ts, src/tools/mongodb/mongodbTool.ts
Uses @napi-rs/keyring to store the credentials from the state in the OS secure storage location.
Additionally, reactors `State` to have a `persistent` field which gets stored and `session` field where we can add global state that should not persist across launches. For now, this is only the `NodeDriverServiceProvider`, which was previously in a now-deleted `MongoDBToolState`.
The node library we're using is a wrapper around https://github.com/open-source-cooperative/keyring-rs, which is a rust-based implementation wrapping the native credential stores for most desktop operating systems.
Fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/20
=> feat: refactor state, store it securely

src/common/atlas/apiClient.ts, src/tools/atlas/createAccessList.ts, src/tools/atlas/tools.ts
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/36
=> feat: add currentIp option atlas-create-access-list tool

.github/workflows/publish.yaml, .github/workflows/version_bump.yaml, .npmrc, CONTRIBUTING.md, README.md
updates docs and improves release process
=> ci: improve release process

src/tools/mongodb/metadata/connect.ts, tests/integration/tools/mongodb/metadata/connect.test.ts
If the user has a configured connection string and the connect fails (e.g. due to the model infering an incorrect connection string from the code), suggest using the config connection string instead.
Fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/73
=> feat: suggest the config connection string on connect failure

src/tools/mongodb/create/createCollection.ts, src/tools/mongodb/metadata/listCollections.ts, src/tools/mongodb/tools.ts, tests/integration/helpers.ts, tests/integration/tools/mongodb/create/createCollection.test.ts, tests/integration/tools/mongodb/metadata/connect.test.ts, tests/integration/tools/mongodb/metadata/listCollections.test.ts, tests/integration/tools/mongodb/metadata/listDatabases.test.ts
chore: add integration tests for listCollections
=> feat: add createCollection tool

tests/integration/helpers.ts, tests/integration/server.test.ts, tests/integration/tools/mongodb/create/createCollection.test.ts, tests/integration/tools/mongodb/metadata/connect.test.ts, tests/integration/tools/mongodb/metadata/listCollections.test.ts, tests/integration/tools/mongodb/metadata/listDatabases.test.ts, tests/integration/tools/mongodb/read/count.test.ts
Noticed that we're always running all the setup functions, so it made sense to just combine them into one.
=> chore: refactor integration test setup

src/server.ts, src/tools/mongodb/metadata/connect.ts, tests/integration/helpers.ts, tests/integration/tools/mongodb/metadata/connect.test.ts
Fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/80
=> fix: tweak the connect tool to prefer preconfigured connection string

tests/integration/helpers.ts
Looks like we lost the `mongoClient?.close()` cleanup in https://github.com/mongodb-js/mongodb-mcp-server/pull/83, which caused jest to complain with `A worker process has failed to exit gracefully and has been force exited`.
=> fix: close mongo client between runs

README.md, src/common/atlas/apiClient.ts, src/session.ts, src/tools/atlas/atlasTool.ts, src/tools/atlas/createAccessList.ts, src/tools/atlas/createDBUser.ts, src/tools/atlas/createFreeCluster.ts, src/tools/atlas/createProject.ts, src/tools/atlas/inspectAccessList.ts, src/tools/atlas/inspectCluster.ts, src/tools/atlas/listClusters.ts, src/tools/atlas/listDBUsers.ts, src/tools/atlas/listOrgs.ts, src/tools/atlas/listProjects.ts, src/tools/tool.ts, tests/integration/tools/atlas/accessLists.test.ts, tests/integration/tools/atlas/atlasHelpers.ts, tests/integration/tools/atlas/clusters.test.ts, tests/integration/tools/atlas/dbUsers.test.ts, tests/integration/tools/atlas/projects.test.ts
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/93
=> feat: hide atlas tools when not configured

src/tools/mongodb/metadata/collectionSchema.ts, src/tools/mongodb/metadata/collectionStorageSize.ts, src/tools/mongodb/mongodbTool.ts, src/tools/tool.ts, tests/integration/helpers.ts, tests/integration/tools/mongodb/create/createCollection.test.ts, tests/integration/tools/mongodb/create/createIndex.test.ts, tests/integration/tools/mongodb/create/insertMany.test.ts, tests/integration/tools/mongodb/delete/deleteMany.test.ts, tests/integration/tools/mongodb/delete/dropCollection.test.ts, tests/integration/tools/mongodb/delete/dropDatabase.test.ts, tests/integration/tools/mongodb/metadata/collectionSchema.test.ts, tests/integration/tools/mongodb/metadata/collectionStorageSize.test.ts, tests/integration/tools/mongodb/metadata/connect.test.ts, tests/integration/tools/mongodb/metadata/listCollections.test.ts, tests/integration/tools/mongodb/metadata/listDatabases.test.ts, tests/integration/tools/mongodb/read/count.test.ts
This PR adds integration tests and fixes issues discovered for the following metadata actions:
- `collection-schema`. Here we're additionally changing the response from table to json as the table was getting quite unwieldy with nested fields.
- `collection-storage-size`
This is a bit a hairy as at some point I got annoyed by some of the more repetitive tests, so extracted helpers for them which resulted in more changes than I planned for. In most files the changes are purely moving functionality to helpers, while the newly created files contain the actual new code.
=> chore: add tests for metadata actions

tests/integration/tools/atlas/accessLists.test.ts, tests/integration/tools/atlas/clusters.test.ts, tests/integration/tools/atlas/dbUsers.test.ts, tests/integration/tools/atlas/orgs.test.ts, tests/integration/tools/atlas/projects.test.ts, tests/integration/tools/mongodb/create/createCollection.test.ts, tests/integration/tools/mongodb/create/createIndex.test.ts, tests/integration/tools/mongodb/create/insertMany.test.ts, tests/integration/tools/mongodb/delete/deleteMany.test.ts, tests/integration/tools/mongodb/delete/dropCollection.test.ts, tests/integration/tools/mongodb/delete/dropDatabase.test.ts, tests/integration/tools/mongodb/metadata/collectionSchema.test.ts, tests/integration/tools/mongodb/metadata/collectionStorageSize.test.ts, tests/integration/tools/mongodb/metadata/connect.test.ts, tests/integration/tools/mongodb/metadata/listCollections.test.ts, tests/integration/tools/mongodb/metadata/listDatabases.test.ts, tests/integration/tools/mongodb/read/count.test.ts
fixes a bug with some method renames in tests
=> fix: tests

src/tools/mongodb/metadata/explain.ts, src/tools/mongodb/update/renameCollection.ts, src/tools/mongodb/update/updateMany.ts, tests/integration/tools/mongodb/metadata/explain.test.ts, tests/integration/tools/mongodb/update/renameCollection.test.ts, tests/integration/tools/mongodb/update/updateMany.test.ts
Add final set of tests for updateMany, renameCollection, and explain.
=> chore: add remaining mongodb integration tests

src/tools/atlas/listProjects.ts
adds org information into `atlas-list-projects` tool
=> feat: add org in atlas-list-projects

src/server.ts, src/telemetry/telemetry.ts, src/telemetry/types.ts
=> chore: add server events

.github/workflows/prepare_release.yaml
aims to fix duplicated v on release bump process (example https://github.com/mongodb-js/mongodb-mcp-server/pull/124)
=> fix: duplicated v on version bump

src/tools/atlas/create/createAccessList.ts, src/tools/atlas/create/createDBUser.ts, src/tools/atlas/create/createFreeCluster.ts, src/tools/atlas/create/createProject.ts, src/tools/atlas/read/inspectAccessList.ts, src/tools/atlas/read/inspectCluster.ts, src/tools/atlas/read/listClusters.ts, src/tools/atlas/read/listDBUsers.ts, src/tools/atlas/read/listOrgs.ts, src/tools/atlas/read/listProjects.ts, src/tools/atlas/tools.ts
renaming files to follow same coding standards between atlas and mongodb
=> chore: follow tools structure in atlas tools

src/common/atlas/apiClient.ts, src/telemetry/constants.ts, src/telemetry/telemetry.ts, src/telemetry/types.ts
- add a boolean value if the user has atlas api keys and if the user has connection string set
=> chore: add config flags

README.md, src/config.ts, src/logger.ts, src/server.ts, src/telemetry/types.ts, src/tools/tool.ts, tests/integration/server.test.ts
=> feat: add readOnly flag

src/tools/mongodb/create/insertMany.ts, src/tools/mongodb/delete/deleteMany.ts, src/tools/mongodb/read/aggregate.ts, src/tools/mongodb/read/count.ts, src/tools/mongodb/read/find.ts, src/tools/mongodb/update/updateMany.ts
Fixes #139.
Needs additional testing with other editors to ensure a record of unknowns is similarly respected. Tested with Claude.
=> fix: use record instead of a passthrough object

.vscode/launch.json, eslint.config.js, package-lock.json, package.json, scripts/apply.ts, scripts/filter.ts, src/common/atlas/apiClient.ts, src/server.ts, src/telemetry/eventCache.ts, src/telemetry/telemetry.ts, src/telemetry/types.ts, src/tools/tool.ts, tests/integration/inMemoryTransport.ts, tests/integration/tools/atlas/atlasHelpers.ts, tests/unit/telemetry.test.ts, tsconfig.build.json, tsconfig.jest.json, tsconfig.json, tsconfig.lint.json
We have been running lint which did catch most TypeScript errors but there's more complex type issues which arise from the TypeScript compiler itself. This adds a type check step and fixes existing issues with it.
There is also a slight reorganization of the common properties appending mechanism to prepare for delaying device ID resolution later
=> chore: add type check for CI

src/logger.ts, src/server.ts, src/session.ts, src/telemetry/telemetry.ts, src/tools/atlas/atlasTool.ts, src/tools/mongodb/mongodbTool.ts, src/tools/tool.ts, tests/integration/helpers.ts, tests/integration/server.test.ts, tests/integration/tools/atlas/atlasHelpers.ts, tests/integration/tools/mongodb/mongodbHelpers.ts, tests/unit/telemetry.test.ts
- infers the values from args
- if using a mongodb tool, checks if it's connected to an atlas cluster
=> chore: add orgId and projectid

eslint.config.js, jest.config.ts, package.json, tests/integration/tools/mongodb/mongodbHelpers.ts, tests/unit/telemetry.test.ts, tsconfig.jest.json
We did not have a full ESM configuration for jest and therefore had a discrepancy between our build vs test. This discrepancy leads to issues with CommonJS modules.
=> fix: use proper ESM with jest

src/tools/atlas/read/inspectCluster.ts, src/tools/atlas/read/listClusters.ts
adds 2 columns to atlas-list-clusters and atlas-inspect-cluster
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/89
=> fix: add atlas instance size

src/server.ts
removes connection string from resource and add some discoverability to atlas tools
=> fix: config resource

package-lock.json, package.json, src/logger.ts, src/telemetry/constants.ts, src/telemetry/device-id.ts
Uses `node-machine-id` and adds the necessary modifications to make it consistent with Atlas CLI (and other tools).
=> feat: use node-machine-id

src/logger.ts, src/session.ts, src/tools/atlas/metadata/connectCluster.ts, src/tools/tool.ts
This essentially keeps trying to connect because after user is created it might take some time for it to be available.
note: also making deletion of user async on disconnect to reduce change of timeout
=> fix: bad auth error

README.md
- defaults docs to mcpServers 
- adds a note about expected syntax discrepancies
=> chore: update quickstart with mcpServers

.github/workflows/code_health.yaml, .github/workflows/code_health_fork.yaml
We expose credentials in Atlas tests at the moment so we will skip them and coverage report checks for external forks and dependabot.
=> chore: skip Atlas Tests and don't track coverage for fork contributions

.github/workflows/check.yml, .github/workflows/code_health.yaml, .github/workflows/code_health_fork.yaml
- Renames lint to checks
- Moves dependency checks to the main checks workflow
- Enables the checks workflow to run on forks
=> fix: fork checks

README.md
- updates some client/key references to mention service accounts, closes https://github.com/mongodb-js/mongodb-mcp-server/issues/208
=> chore: update docs with more Service Accounts mentions

README.md
=> chore: enforce access list

README.md
Added command line setup to explain how to run the mcp server.
=> docs: improve getting started experience

src/helpers/EJsonTransport.ts, src/index.ts, tests/integration/helpers.ts, tests/integration/tools/mongodb/read/find.test.ts, tests/unit/EJsonTransport.test.ts
This works around the issue where we receive bson types serialized as ejson, but not converted into the corresponding types.
Fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/211
=> fix: use ejson parsing for stdio messages

.github/ISSUE_TEMPLATE/bug_report.yml
- adds a placeholder so that users can provide the MCP Server Version
=> chore: update issue template

src/common/atlas/apiClient.ts, src/server.ts, tests/integration/helpers.ts, tests/unit/apiClient.test.ts
- improves send events to make it clearer when we send auth/unauth
- adds one more test
=> fix: improve uncaught exception for getAccessToken

.github/workflows/stale.yml
- based on AtlasCLI GH action, auto-closes issues after 30 days
=> chore: auto-close stale issues

README.md
- Corrects the description of `atlas-create-db-user`
- Closes #239
=> chore: corrects the description of atlas-create-db-user

.github/workflows/check-pr-title.yml, CONTRIBUTING.md
To make our commit messages more consistent as with other DevTools repos, adds a PR title check without enforcing Jira tickets being included for the time being.
=> chore(ci): add a PR title check workflow

README.md
I scraped and tokenized the repository to test its integration with base models. While doing so, I noticed that examples using a non-localhost connection string confused tools like Copilot and Cursor, causing them to generate references to non-existent hosts.
This small change modifies the connection strings in the examples to default to localhost. With this adjustment, tools like MCP instantly align with the base model MongoDB setup and provide much more accurate recommendations.
=> chore: base model SEO change

src/tools/mongodb/read/collectionSearchIndexes.ts, src/tools/mongodb/tools.ts, tests/integration/helpers.ts, tests/integration/tools/atlas-search/read/collectionSearchIndexes.test.ts, tests/integration/tools/mongodb/read/collectionSearchIndexes.test.ts
Adding tool support for listSearchIndexes utility
Shell code added. Waiting for test env setup before submitting actual tests.
=> feat: support for listing search indexes

src/tools/mongodb/delete/dropSearchIndex.ts, src/tools/mongodb/mongodbTool.ts, src/tools/mongodb/tools.ts
Add drop-search-index tool
Tested manually with VS code + Copilot and Claude 3.5
Unit/Integration tests will be added in a separate PR
=> feat: Add drop-search-index tool

src/tools/mongodb/create/createVectorIndex.ts, src/tools/mongodb/mongodbTool.ts, src/tools/mongodb/tools.ts, src/tools/mongodb/update/updateVectorIndex.ts
Add create and update for a vector index.
Manual testing included below. Test functions will be added in a separate PR.
It also works with a more free-form request
=> feat: Add vector index create and update

src/tools/mongodb/create/createSearchIndex.ts, src/tools/mongodb/mongodbTool.ts, src/tools/mongodb/tools.ts, src/tools/mongodb/update/updateSearchIndex.ts
This is specifically for search indexes. The create vector index definition seems sufficiently different that I think it's worth separating.
VSCode copilot at least from my testing does better at distinguishing the two and understanding the fields to set when they are separate.
Tests will be added in a separate PR.
=> feat: create and update Search Index

src/server.ts, src/tools/playground/runPipeline.ts, src/tools/playground/tools.ts, src/tools/tool.ts, tests/integration/tools/playground/runPipeline.test.ts
Add a new `RunPipeline` tool that can execute aggregation pipeline without requiring an Atlas account, cluster, or collection.
The tool accepts a set of documents, an aggregation pipeline, and a search index definition, and runs them against [the Search Playground.](https://search-playground.mongodb.com/) The Search Playground internally creates an ephemeral collection and executes the pipeline in a temporary environment.
Manual testing + integration test. More tests will be added in the following prs.
**What would be the result of query?**
**Is the query syntax correct?**
**Why $search doesn't return first doc?**
=> feat: Add RunPipeline tool

scripts/apply.ts, src/common/atlas/cluster.ts, src/logger.ts, src/tools/atlas/create/createProject.ts, src/tools/atlas/read/listProjects.ts, src/tools/tool.ts, tests/integration/tools/atlas/accessLists.test.ts, tests/integration/tools/atlas/alerts.test.ts, tests/integration/tools/atlas/atlasHelpers.ts, tests/integration/tools/atlas/clusters.test.ts, tests/integration/tools/atlas/dbUsers.test.ts, tests/integration/tools/atlas/orgs.test.ts, tests/integration/tools/atlas/projects.test.ts, tests/integration/tools/mongodb/create/createCollection.test.ts, tests/integration/tools/mongodb/create/createIndex.test.ts, tests/integration/tools/mongodb/create/insertMany.test.ts, tests/integration/tools/mongodb/delete/dropCollection.test.ts, tests/integration/tools/mongodb/metadata/collectionSchema.test.ts, tests/integration/tools/mongodb/metadata/dbStats.test.ts, tests/integration/tools/mongodb/metadata/explain.test.ts, tests/integration/tools/mongodb/metadata/listCollections.test.ts, tests/integration/tools/mongodb/metadata/listDatabases.test.ts, tests/integration/tools/mongodb/metadata/logs.test.ts, tests/integration/tools/mongodb/read/aggregate.test.ts, tests/integration/tools/mongodb/read/collectionIndexes.test.ts, tests/integration/tools/mongodb/read/find.test.ts, tests/integration/tools/mongodb/update/renameCollection.test.ts, tests/unit/EJsonTransport.test.ts, tests/unit/session.test.ts, tsconfig.build.json
closes https://github.com/mongodb-js/mongodb-mcp-server/issues/184
=> chore: enable noUncheckedIndexedAccess 

src/index.ts
closes https://github.com/mongodb-js/mongodb-mcp-server/issues/279
- adds support for handling other signals
- [MCP-10](https://jira.mongodb.org/browse/MCP-10)
=> chore: handle other signals

src/common/playground/playgroundClient.ts, src/tools/playground/runPipeline.ts, tests/integration/tools/playground/runPipeline.test.ts
Adds `PlaygroundClient` class that handles Search Playground requests, abstracting low-level details from MCP tools.
Mocks `PlaygroundClient` in the tests. Adds success and error tests.
No changes to tool behavior.
=> chore: adds PlaygroundClient client and tests for RunPipeline tool

src/logger.ts, src/server.ts, src/telemetry/telemetry.ts, src/telemetry/types.ts, src/tools/tool.ts, tests/integration/telemetry.test.ts, tests/unit/telemetry.test.ts
Reverts mongodb-js/mongodb-mcp-server#298
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/320
=> revert: rollback "chore: add is_container_env to telemetry MCP-2

README.md
When I opened the readme page in Windsurf, I noticed a few broken links.
Fixed broken internal links in the readme:
- `#getting-started` did not exist, put an anchor under the table of contents
- The `contributing` link was broken because there was a space between `🤝` and `Contributing` in the title
=> fix: Broken internal urls in readme

src/telemetry/telemetry.ts, src/telemetry/types.ts, tests/integration/telemetry.test.ts, tests/unit/telemetry.test.ts
changes were initially introduced at https://github.com/mongodb-js/mongodb-mcp-server/pull/298 which caused https://github.com/mongodb-js/mongodb-mcp-server/issues/320 and reverted at https://github.com/mongodb-js/mongodb-mcp-server/pull/330, I'm adding it back without any refactorings
=> chore: reinstate telemetry/docker change after revert MCP-49

src/logger.ts, src/session.ts, src/tools/atlas/metadata/connectCluster.ts, src/tools/mongodb/mongodbTool.ts, tests/integration/tools/atlas/clusters.test.ts
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/321
turn `atlas-connect-cluster` tool into an async tool. Unfortunately, rely on atlas user creation api to connect, sometimes the propagation time of the user from control plane to the data plane can take time, there is no state to query other than check if user has access to DB.
=> fix: turn atlas-connect-cluster async

.vscode/launch.json, src/common/atlas/apiClient.ts, src/logger.ts, src/server.ts, src/session.ts, src/tools/mongodb/metadata/connect.ts, tests/integration/helpers.ts
revoke atlas access tokens on server shutdown [MCP-53]
=> chore: revoke access tokens on server shutdown [MCP-53]

.github/workflows/code_health_fork.yaml, .github/workflows/dependabot_pr.yaml
fix dependabot PRs not running CI after merge
=> fix: dependabot PRs were not running CI after merge

.github/workflows/jira-issue.yml
- Adds automation to create an MCP project JIRA ticket for triage
=> chore: add JIRA issue automation - [MCP-3] 

package.json, src/index.ts, src/transports/base.ts, src/transports/stdio.ts, src/transports/streamableHttp.ts, tests/integration/transports/stdio.test.ts, tests/integration/transports/streamableHttp.test.ts, tests/unit/transports/stdio.test.ts, tests/unit/transports/streamableHttp.test.ts
moves http transport to be created on post as opposed to one per process
Note: this is a prereq for session management
=> refactor: move http server

.vscode/launch.json, README.md, package.json, src/common/logger.ts, src/common/sessionStore.ts, src/index.ts, src/transports/streamableHttp.ts, tests/integration/transports/stdio.test.ts, tests/integration/transports/streamableHttp.test.ts
add session management for streamableHttp
=> feat: add session management for streamableHttp [MCP-52]

.github/workflows/jira-issue.yml
- Adds both teams as assigned for triage
- Adds a link to the description
=> chore: add assigned teams and description

.github/workflows/jira-issue.yml
- Comment on issue only if it succeeds and remove comment
=> fix: remove comment

.github/workflows/accuracy-tests.yml
The workflow earlier was restricted to workflow_dispatch and pull requests with labels accuracy-tests because of the `if` check. This PR, expands the check itself to allow workflow to run on other valid conditions as well.
=> chore: allow workflow to trigger on push to main

src/common/session.ts, src/resources/common/config.ts, src/resources/common/debug.ts, src/resources/resource.ts, src/resources/resources.ts, src/server.ts, tests/unit/resources/common/debug.test.ts
Resources can listen to events on the session and their arguments, and reduces the current state with the argument to provide a new state.
This way this is type safe and declarative, mimicking how tools work.
=> chore: Reactive resource support for debugging connectivity MCP-80

.github/workflows/dependabot_pr.yaml
Dependabot doesn't have access to repo secrets, which is why we must use `pull_request_target` event trigger.
=> chore: use pull_request_target for dependabot prs

eslint.config.js, src/common/atlas/apiClient.ts, src/common/atlas/cluster.ts, src/tools/atlas/connect/connectCluster.ts, tsconfig.build.json
Enables a few extra eslint/ts rules and fixes the issues detected by them:
=> chore: enable some eslint rules

src/common/atlas/accessListUtils.ts, src/common/atlas/apiClient.ts, src/common/atlas/cluster.ts, src/common/logger.ts, src/common/session.ts, src/common/sessionStore.ts, src/index.ts, src/resources/resource.ts, src/server.ts, src/telemetry/telemetry.ts, src/tools/atlas/atlasTool.ts, src/tools/atlas/connect/connectCluster.ts, src/tools/mongodb/mongodbTool.ts, src/tools/tool.ts, src/transports/base.ts, src/transports/stdio.ts, src/transports/streamableHttp.ts, tests/integration/common/apiClient.test.ts, tests/integration/helpers.ts, tests/integration/telemetry.test.ts, tests/integration/tools/mongodb/metadata/listDatabases.test.ts, tests/unit/accessListUtils.test.ts, tests/unit/common/apiClient.test.ts, tests/unit/common/session.test.ts, tests/unit/logger.test.ts, tests/unit/telemetry.test.ts
This refactoring removes the global logger and instead creates a session-scoped logger for each session, which is then used by the whole server machinery. Additionally, we add a session id attribute once the session is bound to ensure that is included in the log messages.
The way this works is we create a composite logger that includes all configured loggers for the transport manager. Then as we create sessions, for each session we create a new composite logger that includes the transport logger and the MCP logger (if configured). Then all tools and api clients will use the session logger.
=> fix: remove global logger MCP-103

.github/workflows/check.yml, package-lock.json, package.json, src/common/config.ts, src/common/connectionManager.ts, src/index.ts, src/lib.ts, src/resources/common/config.ts, src/server.ts, src/tools/atlas/connect/connectCluster.ts, src/tools/mongodb/mongodbTool.ts, tests/integration/common/connectionManager.test.ts, tests/integration/tools/mongodb/connect/connect.test.ts, tests/unit/common/config.test.ts, tests/unit/common/session.test.ts
Use mongosh argument parser to generate the connection string that is going to be used to connect to MongoDB, aligning with how mongosh does it and making sure we support additional authentication mechanisms. It removes a bunch of flags and types not necessary now with the consolidation.
There will be integration tests for each of the supported connection types when playing each of their tasks. Specific support is out of the scope of this PR.
=> chore: add arg-parser and put the config under test MCP-86

README.md
Reverts mongodb-js/mongodb-mcp-server#438
=> Revert "docs: add gateways and proxies section to README"

src/common/exportsManager.ts, src/tools/mongodb/read/export.ts, src/tools/mongodb/read/find.ts, tests/accuracy/export.test.ts, tests/integration/resources/exportedData.test.ts, tests/integration/tools/mongodb/read/export.test.ts
Extends the current export tool to allow exporting aggregations as well.
=> feat: adds support for exporting aggregations MCP-16

tests/accuracy/export.test.ts
Looks like we had some tests failing because the model was providing the export title but we weren't expecting it.
=> fix: fix expectations for export accuracy tests

src/common/atlas/roles.ts, src/tools/atlas/connect/connectCluster.ts, tests/unit/common/roles.test.ts
- Defaults to readOnly DB user role unless all tools are enabled
=> fix: atlas connectCluster defaults to readOnly DB roles - MCP-125

.github/workflows/code_health.yaml, .github/workflows/code_health_fork.yaml, tests/integration/tools/atlas/orgs.test.ts
- this fixes the issue where we were validating the size of the response. now we just check if the expected org has been found
=> fix: update atlas integration tests -- MCP-98

src/tools/atlas/connect/connectCluster.ts
- Adds the URL about the temporary user role
=> chore: update user description

src/common/logger.ts, src/index.ts, src/transports/streamableHttp.ts
This makes it so the server sends a ping every 30 seconds to connected clients to ensure the connection is still alive. After 3 failed pings, we close the transport.
=> fix: add a ping loop for http transport clients

.github/workflows/check.yml, package-lock.json, package.json, src/common/logger.ts, src/server.ts, src/transports/base.ts, tests/unit/logger.test.ts
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/485
fixes https://github.com/mongodb-js/mongodb-mcp-server/issues/454
=> fix: handle setLogLevel requests

src/common/logger.ts, src/server.ts, tests/unit/logger.test.ts
This is a follow-up on https://github.com/mongodb-js/mongodb-mcp-server/pull/486 - it adds an extra test to ensure our log levels array is exhaustive and a parameter validation for the http endpoint.
=> chore: add some extra log level validations

.github/workflows/code_health.yaml, tests/integration/helpers.ts, tests/integration/tools/atlas/atlasHelpers.ts
- fixes the Atlas test command
- Adds IP to access list of any created project test
- Checks that apiClient has credentials and updates a mock for validation
=> ci: add ipAccessList after creating project

src/tools/tool.ts, tests/integration/common/connectionManager.oidc.test.ts
- Connect used to be under `metadata` category, after we updated it, it got removed from the `readOnly` tools. This is needed to be able to use read operations.
=> fix: allow connect tool on readOnly mode

src/common/atlas/accessListUtils.ts, src/tools/atlas/connect/connectCluster.ts, tests/integration/tools/atlas/atlasHelpers.ts, tests/integration/tools/atlas/clusters.test.ts
- MCP-124
- Adds more messages about the resources created to be able to connect to an atlas cluster
=> feat: add more details about atlas connect flow - MCP-124

.github/workflows/publish.yaml
The earlier script was not for bash, maybe for windows CMD / Powershell (based on the usage of Write-Output command) so I translated the script to bash in this PR.
=> chore: fix release channel detection script

tests/accuracy/createDeployment.test.ts, tests/accuracy/deleteDeployment.test.ts, tests/accuracy/listDeployments.test.ts
Jira: [MCP-178](https://jira.mongodb.org/browse/MCP-178)
=> feat(atlas-local): Accuracy tests for Atlas Local

package-lock.json, package.json
VSCode project works(not directly) with yargs-parser@21 and our project pulls in version 22. The dependency resolution in VSCode resolves yargs-parser to version 21 and thus the usage of this dependency in the imported mcp-server-code breaks.
Ideally, we wouldn't have to do this because the imported code in VSCode, theoretically, in no way relies on yargs-parser. But because of our code setup, the yargs-parser does come in the imported path eventually:
1. exporting types and vaues from config.js in lib entry point which imports yargs-parser. Ideally we should re-organise this to different files, one with schema and one with config helpers.
2. imports from config.js in our trasport/base.js which sets up default connectionManager imported from connectionManager.js which further imports …
=> fix: pin yargs-parser to 21 for VSCode compatibility

.github/workflows/publish.yaml
=> fix: use correct expression for the release channel

.github/copilot-instructions.md
New basic copilot instructions for the Copilot reviewer. They are based on:
https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions?tool=webui#creating-path-specific-custom-instructions-1
=> chore: Add a new generic copilot-instructions.md to make copilot more useful on reviews

src/tools/mongodb/metadata/explain.ts, tests/integration/tools/mongodb/metadata/explain.test.ts
While queryPlanner is a good default, there are scenarios where we need more verbose outputs to understand why a query is not acting as expected. For example, executionStats can be useful to see rw locks, disk usage and flow throttling.
I'm not sure how good are models understanding the whole executionPlan, and maybe we need to remove information that might not be relevant for debugging to reduce the context usage, but this is a decent first approach and we can improve later.
This implements the feature request from https://github.com/mongodb-js/mongodb-mcp-server/issues/527
=> feat(explain): Add support for custom verbosity to the explain plan tool

scripts/accuracy/runAccuracyTests.sh, tests/accuracy/collectionIndexes.test.ts, tests/accuracy/explain.test.ts
A small change to bring back accuracy to previous known levels.
=> chore: add missing expectations for accuracy tests

package-lock.json, package.json, src/common/connectionErrorHandler.ts, src/tools/atlasLocal/atlasLocalTool.ts, src/tools/atlasLocal/connect/connectDeployment.ts, src/tools/atlasLocal/tools.ts, tests/accuracy/connectDeployment.test.ts, tests/integration/tools/atlas-local/connectDeployment.test.ts, tests/integration/tools/atlas-local/deleteDeployment.test.ts, tests/integration/tools/atlas/clusters.test.ts
1. Implements tool atlas-local-connect-deployment
3. Adds integration tests
5. Adds accuracy tests
7. Adds hint for connecting for local deployment
=> feat(atlas-local): Adds Atlas Local Connect Deployment tool

src/tools/mongodb/metadata/collectionStorageSize.ts, src/tools/mongodb/read/collectionIndexes.ts, src/tools/mongodb/update/renameCollection.ts
Adds `isError` annotation for handled errors that were missed.
=> chore: add isError annotation for handled errors
